# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-08 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gantt_task',
            name='finish',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='gantt_task',
            name='start',
            field=models.DateField(),
        ),
    ]
