# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-08 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180508_1421'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GANTT_PJT',
            new_name='PROJECT',
        ),
        migrations.RenameModel(
            old_name='GANTT_TASK',
            new_name='TASK',
        ),
    ]
