# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-08 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180508_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name_task',
            field=models.CharField(max_length=14),
        ),
    ]
