# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-10 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180509_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('n', 'Не розпочата'), ('i', 'Незавершена'), ('c', 'Завершена')], default='n', max_length=1),
        ),
    ]
