# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-10 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_task_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
