# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-10 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20180510_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
