# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-14 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20180510_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='responsible',
            field=models.CharField(blank=True, help_text='Введіть головного відповідального за проект', max_length=200, null=True, verbose_name='Відповідальний'),
        ),
        migrations.AddField(
            model_name='task',
            name='overdue_reason',
            field=models.CharField(blank=True, help_text='Якщо завдання прострочено, вкажіть причину, чому це сталося', max_length=1000, null=True, verbose_name='Причина простроченого завдання'),
        ),
        migrations.AddField(
            model_name='task',
            name='performer',
            field=models.CharField(blank=True, help_text='Введіть виконавця завдання, або через кому, якщо їх декілька', max_length=1000, null=True, verbose_name='Виконавець'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='Введіть назву проекту', max_length=500, verbose_name='Назва'),
        ),
    ]
