# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-14 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20180514_0559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проекти (назви і відповідальні)', 'verbose_name_plural': 'Проекти (назви і відповідальні)'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Завдання проектів', 'verbose_name_plural': 'Завдання проектів (деталі)'},
        ),
        migrations.AlterField(
            model_name='task',
            name='performer',
            field=models.CharField(default='Відсутні дані', help_text='Введіть виконавця завдання, або через кому, якщо їх декілька', max_length=1000, verbose_name='Виконавець'),
        ),
    ]
