# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-14 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20180514_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='responsible',
            field=models.CharField(default='Відсутні дані', help_text='Введіть головного відповідального за проект', max_length=200, verbose_name='Відповідальний'),
        ),
    ]
