# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-19 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20180514_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='promizhny_control',
            field=models.IntegerField(default=50, help_text='введіть процент післі якого буде виповняться проміжний контроль', verbose_name='Процент Проміжного Контролю'),
        ),
    ]
