# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-20 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_project_promizhny_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='promizhny',
            field=models.BooleanField(default=False, verbose_name='Проміжний контроль'),
        ),
        migrations.AlterField(
            model_name='project',
            name='promizhny_control',
            field=models.IntegerField(default=50, help_text='введіть процент, післі якого буде виповняться проміжний контроль (за замовчуванням 50%)', verbose_name='Процент Проміжного Контролю'),
        ),
    ]
