# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-20 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20180520_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='overdue',
            field=models.BooleanField(default=False, verbose_name='Прострочена'),
        ),
    ]
