# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-04 11:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20180527_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='control',
            options={'verbose_name': 'розсилка звіту', 'verbose_name_plural': 'розсилка звіту'},
        ),
        migrations.AddField(
            model_name='task',
            name='promizhny_date',
            field=models.DateField(default=datetime.date(1, 1, 1)),
        ),
    ]
