# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-04 18:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20180604_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='change_percent',
            field=models.BooleanField(default=False, verbose_name='Змінити процент'),
        ),
        migrations.AlterField(
            model_name='task',
            name='promizhny_date',
            field=models.DateField(default=datetime.date(1, 1, 1), verbose_name='Дата контролю'),
        ),
    ]
